Repository confident-ai/deepeval, pull requests merged in 2025-10, with the labels that each got.

#2141 Fixed ZeroDivisionError in MultiTurnMCPUseMetric when no tasks are returned
  deepeval/metrics/mcp/multi_turn_mcp_use_metric.py
Labels: awaiting fix

#2151 Amazon bedrock fix to remove default temperature
  deepeval/models/llms/amazon_bedrock_model.py
  docs/integrations/models/amazon-bedrock.mdx
  tests/test_core/test_models/test_amazon_bedrock_param_translation.py
Labels: awaiting docs fix

#2140 Saving trace in Pydanic AI instrumentator for accessing in the future
  deepeval/integrations/pydantic_ai/instrumentator.py
  deepeval/tracing/__init__.py
  deepeval/tracing/trace_context.py
  tests/test_integrations/test_pydanticai/simple_agent.py
Labels: awaiting code fix, awaiting clarification

#2152 Crew AI update
  deepeval/integrations/crewai/__init__.py
  deepeval/integrations/crewai/agent.py
  deepeval/integrations/crewai/handler.py
  deepeval/integrations/crewai/patch.py
  deepeval/integrations/crewai/wrapper.py
  examples/tracing/crewai_tracing.ipynb
  tests/test_integrations/test_crewai/crewai_app.py
Labels: awaiting code fix
